{
 "title": "Outline custom",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Are users using the service?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Access Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(max(increase(shadowsocks_data_bytes{access_key!=\"\"} [1h])) by (access_key, location) > bool 0) by (location)",
     "legendFormat": "1h {{location}}"
    },
    {
     "expr": "sum(max(max_over_time(shadowsocks_data_bytes{access_key!=\"\"} [1d])) by (access_key) > bool 0)",
     "legendFormat": "1d"
    },
    {
     "expr": "sum(max(max_over_time(shadowsocks_data_bytes{access_key!=\"\"} [7d])) by (access_key) > bool 0)",
     "legendFormat": "7d"
    }
   ]
  },
  {
   "title": "Access Key 1h Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(shadowsocks_data_bytes[1h])) by (access_key)",
     "legendFormat": "{{access_key}}"
    }
   ]
  },
  {
   "title": "Total Data usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(shadowsocks_data_bytes{dir=~\"c<p|p>t\"} [1h])) by (location)",
     "legendFormat": "1h {{location}}"
    },
    {
     "expr": "sum(increase(shadowsocks_data_bytes{dir=~\"c<p|p>t\"} [1d]))",
     "legendFormat": "1d"
    },
    {
     "expr": "sum(increase(shadowsocks_data_bytes{dir=~\"c<p|p>t\"} [7d]))",
     "legendFormat": "7d"
    },
    {
     "expr": "sum(increase(shadowsocks_data_bytes{dir=~\"c<p|p>t\"} [4w]))",
     "legendFormat": "4w"
    }
   ]
  },
  { "title": "Is the service healthy?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[10m])",
     "legendFormat": "cpu {{job}}"
    },
    { "expr": "go_goroutines", "legendFormat": "go_goroutines {{job}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "virtual_memory {{job}}" },
    {
     "expr": "shadowsocks_udp_nat_entries_added - shadowsocks_udp_nat_entries_removed",
     "legendFormat": "udp nat entries"
    },
    { "expr": "process_open_fds", "legendFormat": "open_fds {{job}}" }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(shadowsocks_tcp_connection_duration_ms_count [10m])) by (access_key, status)",
     "legendFormat": "count/s {{access_key}} {{status}}"
    },
    {
     "expr": "sum(rate(shadowsocks_tcp_connection_duration_ms_sum [10m])) by (access_key,status) / sum(rate(shadowsocks_tcp_connection_duration_ms_count [10m])) by (access_key, status)",
     "legendFormat": "duration {{access_key}} {{status}}"
    }
   ]
  },
  {
   "title": "Open TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(shadowsocks_tcp_connections_opened) -  sum(shadowsocks_tcp_connections_closed)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(shadowsocks_tcp_connections_closed{status=~\"ERR_.*\"} [10m])) by (status, access_key)",
     "legendFormat": "{{status}} {{access_key}}"
    }
   ]
  },
  {
   "title": "Time to Cipher",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "shadowsocks_time_to_cipher_ms{access_key!=\"\"}",
     "legendFormat": "{{access_key}} {{location}} {{proto}} {{quantile}}"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 1, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Total Access Keys",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shadowsocks_keys" }
   ]
  }
 ]
}